
package com.abaco.servicio.laserfiche;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GestionDocumento", targetNamespace = "http://servicio.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionDocumento {


    /**
     * 
     * @param documentoID
     * @return
     *     returns com.abaco.servicio.laserfiche.Documento
     */
    @WebMethod
    @WebResult(name = "documento", targetNamespace = "")
    @RequestWrapper(localName = "obtenerDoumento", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.ObtenerDoumento")
    @ResponseWrapper(localName = "obtenerDoumentoResponse", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.ObtenerDoumentoResponse")
    public Documento obtenerDoumento(
        @WebParam(name = "documentoID", targetNamespace = "")
        String documentoID);

    /**
     * 
     * @param codigoSocio
     * @param numeroDocumento
     * @return
     *     returns com.abaco.servicio.laserfiche.Mensaje
     */
    @WebMethod
    @WebResult(name = "mensaje", targetNamespace = "")
    @RequestWrapper(localName = "copiarTodoProspectoASocio", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.CopiarTodoProspectoASocio")
    @ResponseWrapper(localName = "copiarTodoProspectoASocioResponse", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.CopiarTodoProspectoASocioResponse")
    public Mensaje copiarTodoProspectoASocio(
        @WebParam(name = "numeroDocumento", targetNamespace = "")
        String numeroDocumento,
        @WebParam(name = "codigoSocio", targetNamespace = "")
        long codigoSocio);

    /**
     * 
     * @param archivo
     * @return
     *     returns com.abaco.servicio.laserfiche.Mensaje
     */
    @WebMethod
    @WebResult(name = "mensaje", targetNamespace = "")
    @RequestWrapper(localName = "guardarArchivo", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.GuardarArchivo")
    @ResponseWrapper(localName = "guardarArchivoResponse", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.GuardarArchivoResponse")
    public Mensaje guardarArchivo(
        @WebParam(name = "archivo", targetNamespace = "")
        Archivo archivo);

    /**
     * 
     * @param rutaArchivo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "rutaSalida", targetNamespace = "")
    @RequestWrapper(localName = "conviertirArchivoAPDF", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.ConviertirArchivoAPDF")
    @ResponseWrapper(localName = "conviertirArchivoAPDFResponse", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.ConviertirArchivoAPDFResponse")
    public String conviertirArchivoAPDF(
        @WebParam(name = "rutaArchivo", targetNamespace = "")
        String rutaArchivo);

    /**
     * 
     * @param archivoBusqueda
     * @return
     *     returns com.abaco.servicio.laserfiche.Archivo
     */
    @WebMethod
    @WebResult(name = "archivoRespuesta", targetNamespace = "")
    @RequestWrapper(localName = "obtenerArchivo", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.ObtenerArchivo")
    @ResponseWrapper(localName = "obtenerArchivoResponse", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.ObtenerArchivoResponse")
    public Archivo obtenerArchivo(
        @WebParam(name = "archivoBusqueda", targetNamespace = "")
        Archivo archivoBusqueda);

    /**
     * 
     * @param documento
     * @return
     *     returns com.abaco.servicio.laserfiche.Mensaje
     */
    @WebMethod
    @WebResult(name = "mensaje", targetNamespace = "")
    @RequestWrapper(localName = "guardarDocumento", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.GuardarDocumento")
    @ResponseWrapper(localName = "guardarDocumentoResponse", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.GuardarDocumentoResponse")
    public Mensaje guardarDocumento(
        @WebParam(name = "documento", targetNamespace = "")
        Documento documento);

    /**
     * 
     * @param nombreArchivo
     * @param tipoBusqueda
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "rutas", targetNamespace = "")
    @RequestWrapper(localName = "buscarCarpeta", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.BuscarCarpeta")
    @ResponseWrapper(localName = "buscarCarpetaResponse", targetNamespace = "http://servicio.ws/", className = "com.abaco.servicio.laserfiche.BuscarCarpetaResponse")
    public List<String> buscarCarpeta(
        @WebParam(name = "tipoBusqueda", targetNamespace = "")
        String tipoBusqueda,
        @WebParam(name = "nombreArchivo", targetNamespace = "")
        String nombreArchivo);

}
